import type { Metadata } from "next";
import { Roboto, Londrina_Solid, Sen } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const londrinaSolid = Londrina_Solid({
  variable: "--font-londrina-solid",
  subsets: ["latin"],
  weight: '300'
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const sen = Sen({
  variable: "--font-sen",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${londrinaSolid.variable} ${roboto.variable} ${sen.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
